traffic:
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: depiser
      port: 1433
      database: traffic
      schema: dbo
      user: dbtuser
      password: 'AM.most123'
      encrypt: true
      trust_cert: false
      authentication: SqlPassword
  target: dev